// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaiwoluqcrsnmjkxdcqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhaXdvbHVxY3Jzbm1qa3hkY3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDc1OTgsImV4cCI6MjA1ODY4MzU5OH0.ZrKU0fQCO8IKjH7EZEpCNLy485hzkSDBv8rYU5_eLf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);